#!/usr/bin/python3

def raise_exception_msg(message=""):
    """Fuction that raises a NameError with a message"""
    raise NameError(message)
